### ISSUE TITLE
unable to register an account

### ISSUE THREAD

**Issue by by-sknight** [bilalcaliskan/oreilly-trial#146]
Since at least August 19th, it has been impossible to successfully register an account.

```
# ./oreilly-trial --verbose
6:11AM INF oreilly-trial is started! appVersion=2.2.14 buildDate=2023-08-04T18:13:49Z gitCommit=7a1a105 goArch=amd64 goOS=linux goVersion=go1.20.6
6:11AM DBG trying to set request headers
6:11AM DBG sending request with http client url=https://learning.oreilly.com/api/v1/registration/individual/
```

**Comment by TeaEwan** [comment]
Same question.

**Comment by yo80106** [comment]
I got same issue.

**Comment by bilalcaliskan** [comment]
i can verify that it is the same on my own. on it. thanks for reporting!

**Comment by bilalcaliskan** [comment]
still investigating but just a heads up; ive noticed that oreilly changed its API so its timing out actually. but with the new API address, both browser and our app throws 403.

**Comment by by-sknight** [comment]
where can I find oreilly api? I only found the search API.  
[O'Reilly Platform Search API](https://www.oreilly.com/online-learning/integration-docs/search.html)

**Comment by bilalcaliskan** [comment]
@by-sknight you can discover using network tool on your browser but there is no API documentation.

**Comment by by-sknight** [comment]
@bilalcaliskan Thanks, I forgot about this method. When I see the api in the link, I'm just looking for the api documentation.

**Comment by ForeGuards** [comment]
any news about this issue?

**Comment by bilalcaliskan** [comment]
still no luck. last chance is acting like a browser with a selenium library.

**Comment by fs30000** [comment]
Here it times out:

6:01PM INF oreilly-trial is started! appVersion=2.2.14 buildDate=2023-08-04T18:13:49Z gitCommit=7a1a105 goArch=am                             d64 goOS=linux goVersion=go1.20.6
6:06PM WRN an error occurred while generating email with specific domain error="unable to do http request to remote host https://learning.oreilly.com/api/v1/registration/individual/: Post \"https://learning.oreilly.com/api/v1/registration/individual/\": read t            cp 192.168.1.2:42978->2.16.8.8:443: read: connection timed out" attempt=1 domain=RG9tYWluOjIw mail=4e46crpa@mailpwr.com

**Comment by loudywen** [comment]
> still no luck. last chance is acting like a browser with a selenium library.

that is the way to go

**Comment by bilalcaliskan** [comment]
couple of news; oreilly is now somehow protecting the API with a cookie and without that cookie, we are encountering the error you all see. sadly i could not find a way to obtain this cookie yet.

contributions are welcomed by the way.

**Comment by by-sknight** [comment]
acm professional members can access o'reilly's resources for $75 per year.

[Skills Bundle Add-on](https://learning.acm.org/skills-bundle)

**Comment by AlexDias95** [comment]
@bilalcaliskan any news from this?
