### ISSUE TITLE
Can't even install

### ISSUE THREAD

**Issue by HarshscGithub** [bilalcaliskan/oreilly-trial#153]
==> Tapping joshsagredo/tap
fatal: could not create leading directories of '/opt/homebrew/Library/Taps/joshsagredo/homebrew-tap': Permission denied
Error: Failure while executing; `git clone https://github.com/joshsagredo/homebrew-tap /opt/homebrew/Library/Taps/joshsagredo/homebrew-tap --origin=origin --template= --config core.fsmonitor=false` exited with 128.

And Now it requires authenticaton

**Comment by bilalcaliskan** [comment]
this project is archived and does not work anymore because of the security precautions of Oreilly. Thanks for your interest anyway.
